// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOWW9hQnauuFbpflWjFxt_xuRjRDRUb5I',
    appId: '1:2095942501:web:e31fd565203c66ca6bef8c',
    messagingSenderId: '2095942501',
    projectId: 'projeto-faculdade-42b24',
    authDomain: 'projeto-faculdade-42b24.firebaseapp.com',
    storageBucket: 'projeto-faculdade-42b24.appspot.com',
    measurementId: 'G-9BP7DGMC7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8O0tUtZxvKYm_faIg_ADxwyuF-eTRKQc',
    appId: '1:2095942501:android:b636a0b578d0bd546bef8c',
    messagingSenderId: '2095942501',
    projectId: 'projeto-faculdade-42b24',
    storageBucket: 'projeto-faculdade-42b24.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOWW9hQnauuFbpflWjFxt_xuRjRDRUb5I',
    appId: '1:2095942501:web:c70752887d88ea956bef8c',
    messagingSenderId: '2095942501',
    projectId: 'projeto-faculdade-42b24',
    authDomain: 'projeto-faculdade-42b24.firebaseapp.com',
    storageBucket: 'projeto-faculdade-42b24.appspot.com',
    measurementId: 'G-QTCQM7TJ58',
  );
}
